In [21]:
import pandas as pd
df = pd.read_csv('ptt2.csv')

In [23]:
df.columns = ['date', 'vix', 'BI', 'close', 'pos', 'neg', 'seg']
df = df.fillna(method='ffill')[2:-4]

In [25]:
df.to_csv('ptt.csv',index=False)

In [24]:
df

           date    vix        BI    close   pos   neg          seg
2    2019-12-02  14.44  0.287682  4606.24  18.0  22.0     .%,億元,美國
3    2019-12-03  14.08  0.074108  4600.59  13.0  12.0     美國,經濟,市場
4    2019-12-04  14.32 -0.204794  4599.14  25.0  21.0     收購,公開,空屋
5    2019-12-05  13.49  0.421213  4618.23  30.0  21.0     銀行,台灣,機制
6    2019-12-06  13.03  0.036368  4611.05  26.0  27.0  美國,u3000,.%
..          ...    ...       ...      ...   ...   ...          ...
559  2021-06-11  17.73 -0.089948  4556.32  94.0  79.0    張苗,獲得幣,恭喜
560  2021-06-12  17.73 -0.089948  4556.32  94.0  79.0    張苗,獲得幣,恭喜
561  2021-06-13  17.73 -0.089948  4556.32  94.0  79.0    張苗,獲得幣,恭喜
562  2021-06-14  17.73 -0.089948  4556.32  94.0  79.0    張苗,獲得幣,恭喜
563  2021-06-15  17.73 -0.089948  4556.32  94.0  79.0    張苗,獲得幣,恭喜

[562 rows x 7 columns]

In [14]:
df

           date    vix        BI    close   pos   neg         seg
0    2019-11-30    NaN -0.510826      NaN   3.0   3.0   美國,非球體,公室
1    2019-12-01    NaN -0.127833      NaN  17.0  27.0  美國,經濟,違反板規
2    2019-12-02  14.44  0.287682  4606.24  18.0  22.0    .%,億元,美國
3    2019-12-03  14.08  0.074108  4600.59  13.0  12.0    美國,經濟,市場
4    2019-12-04  14.32 -0.204794  4599.14  25.0  21.0    收購,公開,空屋
..          ...    ...       ...      ...   ...   ...         ...
559  2021-06-11  17.73       NaN      NaN   NaN   NaN         NaN
560  2021-06-12    NaN       NaN      NaN   NaN   NaN         NaN
561  2021-06-13    NaN       NaN      NaN   NaN   NaN         NaN
562  2021-06-14    NaN       NaN      NaN   NaN   NaN         NaN
563  2021-06-15    NaN       NaN      NaN   NaN   NaN         NaN

[564 rows x 7 columns]